### ISSUE TITLE
congrats!

### ISSUE THREAD

**Issue by fossfreedom** [serdarsen/budgie-advanced-brightness-controller#1]
Hi

Congrats for writing this budgie applet.  This is excellent for the budgie desktop community.

At the moment in Ubuntu Budgie we promote this similar plugin via our budgie-welcome snap/app

 - https://github.com/ilgarmehmetali/budgie-brightness-control-applet (since you are using Ubuntu Budgie its in Software - Applets)

If we also promote this plugin, what advantages have you designed in compared to that plugin?  Would need to explain this in the welcome snap/app.

**Comment by serdarsen** [comment]
@fossfreedom, I am glad you like it. I'm sorry for the late reply.

For this plugin I want to add also another brigtness controller widget for device system back light, but for now i don't know how to do. 

Secondary, right now I'm trying to make a minimal workspace switcher as another applet (it'll show current workspace number, when click it'll show a buttons menu for available workspaces in a Popover ). 

Will you add this to the welcome app. is there something i should do for this. Sorry for my bad English.

**Comment by fossfreedom** [comment]
The workspace idea sounds similar to this 

https://github.com/dgaw/budgie-workspaces-compact

Not sure on the backlight issue. If there was a command line way to switch the backlight on or off you could hook it up to a checkbox toggle event.

I think if you manage to do this this will differentiate this plugin from the existing brightness controller in welcome. So I would then be very happy to showcase your excellent work.

**Comment by serdarsen** [comment]
Yes this is similar. I did not know it was. I found some code about the backlight issue, I will work on it. I will inform you if I manage to do this. thanks again.

**Comment by serdarsen** [comment]
@fossfreedom, I made the changes I wanted. I completed the plugin.

**Comment by fossfreedom** [comment]
Hi - I've raised an issue here to package and to promote via budgie-welcome. https://github.com/UbuntuBudgie/budgie-welcome/issues/180

Please can you create a git release version e.g. v0.1 or v1.0 or something similar so that we know what version we need to package?

**Comment by fossfreedom** [comment]
As an aside "UBrightnessController is an Ubuntu Budgie desktop applet for productivity." in the README.  I think you meant "UBrightnessController is a Budgie Desktop applet for productivity." --> I presume the applet should work on all distro's such as Manjaro, Debian, Solus etc.

**Comment by serdarsen** [comment]
Ok @fossfreedom  I have created a git release version v1.0.0 and I have edited the readme.
