### ISSUE TITLE
Rename the plugin file

### ISSUE THREAD

**Issue by fossfreedom** [serdarsen/budgie-advanced-brightness-controller#10]
Please can the plugin file be renamed from Applet.plugin to "advancedbrightnesscontroller.plugin"

i.e. this was the name for v1.2.3; the reason for the request is two-fold

1. Applet.plugin is generic and may interfere with other similarly named plugins
2. When people upgrade the applet will disappear from the panel - with the old name, the applet will remain in the panel.

**Comment by serdarsen** [comment]
Applet.plugin renamed to advancedbrightnesscontroller.plugin. And meson.build updated as well.
https://github.com/serdarsen/budgie-advanced-brightness-controller/releases/tag/v1.3.1
