### ISSUE TITLE
The applet does not show up on Ubuntu Budgie 17.10

### ISSUE THREAD

**Issue by Jacob-Vlijm** [serdarsen/budgie-advanced-brightness-controller#2]
Installed the applet on Ubuntu Budgie 17.10, but it doesn't show up. Running `budgie-panel --replace &`  shows:

```
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 51, in do_get_panel_widget
    return UBrightnessControllerApplet(uuid)
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 172, in __init__
    self.initBrightness();
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 93, in initBrightness
    self.brightnessValue = self.get_curr_brightness()
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 82, in get_curr_brightness
    self.curr_brightness = int(p.communicate()[0])
ValueError: invalid literal for int() with base 10: b'Could not get or set the value of the backlight: No backlight devices present\n'
```

**Comment by serdarsen** [comment]
@Jacob-Vlijm  

Can you check what does the command bellow prints when you run it in terminal?

`pkexec /usr/lib/gnome-settings-daemon/gsd-backlight-helper --get-max-brightness`

If you are building and running the plugin in a virtual machine it'll probably
return the "Could not get or set the value of the backlight: No backlight devices present" message and the plugin won't work. 

I should have checked this before.

After this, can you check what does the command bellow prints when you run it in terminal?

`xrandr`

**Comment by Jacob-Vlijm** [comment]
The command returns:
`Could not get or set the value of the backlight: No backlight devices present`

xrandr sais:
``
Screen 0: minimum 8 x 8, current 1680 x 1050, maximum 8192 x 8192
DVI-I-0 disconnected (normal left inverted right x axis y axis)
VGA-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 connected primary 1680x1050+0+0 (normal left inverted right x axis y axis) 473mm x 296mm
   1680x1050     59.95*+
   1600x1200     60.00  
   1600x1000     60.00  
   1440x900      59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
``

This is a "real" computer :) (no vm)

**Comment by serdarsen** [comment]
:) I see. @Jacob-Vlijm 

I think it is graphic and grub settings that cause this problem.

According to proxeIO [answer](https://askubuntu.com/a/637842) and Abhishek Prakash [blog post](https://itsfoss.com/fix-brightness-ubuntu-1310/), you can edit grub and if your device using intel graphic card  you can edit your 20-intel.conf file.

**Update Grub**;

1.  `sudo gedit /etc/default/grub`

2.  Change;
    `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"`
     to
    `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=force acpi_osi="`

    Save and exit gedit


3. `sudo update-grub`

   Restart your computer

**Create 20-intel.conf; Intel GFX card only!**

1. check your graphic card
   ` ls /sys/class/backlight/`

   (in my terminal the result is `acpi_video0  intel_backlight`)

2. Create the following configuration file, if it does not exist:
   `sudo touch /usr/share/X11/xorg.conf.d/20-intel.conf`

3. Edit this file.
  ` sudo gedit /usr/share/X11/xorg.conf.d/20-intel.conf`

   Copy & Paste the following lines into the document;


   ```
   Section "Device"
           Identifier  "card0"
           Driver      "intel"
           Option      "Backlight"  "intel_backlight"
           BusID       "PCI:0:2:0"
   EndSection
   ```

   Save and exit the document.

   Restart your computer;

   My settings are the same. This should work.

**Comment by Jacob-Vlijm** [comment]
I have no issues with my keys, I simply have no backlight, which is not available on all systems. Imo the applet should try/except instead of crash.

**Comment by fossfreedom** [comment]
Agree - a bit of error trapping is required to make this a bit more user friendly.  For example - if no brightness control is detected then the slider should be removed and a bit of text added to the popover to say "No backlight detected" ... or words to that effect.

Similarly for the dimmer slider - if the laptop/desktop doesnt have a dimmer ability then maybe just hide that slider.

**Comment by serdarsen** [comment]
I have updated the plugin. Try except blocks added to check whether the Light and Dim tools are available. 
It'll display available widgets.

**Comment by Jacob-Vlijm** [comment]
Congratulations!
Cheers, looks like it works like a charm.
