### ISSUE TITLE
security issue with the installer

### ISSUE THREAD

**Issue by fossfreedom** [serdarsen/budgie-advanced-brightness-controller#3]
Just packaging and I noticed you are giving 777 rights to an exe in the installer - this is a potential security issue since it allows everyone to change that file.  Suggest narrow the rights to 755

In addition the main .py file has executable rights - suggest change to 644

**Comment by serdarsen** [comment]
Ok @fossfreedom tell me if i understand correctly please.

Should I grant the rights as follows ?

sudo chmod -R 755 "${PLUGIN_DIR}/UBrightnessController/ubrightnesscontroller"
sudo chmod -R 644 "${PLUGIN_DIR}/UBrightnessController/UBrightnessController.py"

**Comment by fossfreedom** [comment]
Yep. That looks correct. 👍

On Sun, 29 Apr 2018, 16:53 Serdar ŞEN, <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok @fossfreedom<https://github.com/fossfreedom> tell me if i understand correctly please.

Should I grant the rights as follows ?

sudo chmod -R 755 "${PLUGIN_DIR}/UBrightnessController/ubrightnesscontroller"
sudo chmod -R 644 "${PLUGIN_DIR}/UBrightnessController/UBrightnessController.py"

**Comment by serdarsen** [comment]
I've tried this. 644 is fine for main.py, but 755 could not save the dim value to the ubrightnesscontroller file. it is a cache file to save and to retrive the brightness value.

would that be correct?

sudo chmod -R 666 "${PLUGIN_DIR}/UBrightnessController/ubrightnesscontroller"
sudo chmod -R 644 "${PLUGIN_DIR}/UBrightnessController/UBrightnessController.py"

it works like that.

**Comment by fossfreedom** [comment]
It is account specific data?

You should save data to a .config/ubrightnesscontroller folder not in a global location.

On Sun, 29 Apr 2018, 17:57 Serdar ŞEN, <notifications@github.com<mailto:notifications@github.com>> wrote:

I've tried this. 644 is fine for main.py, but 755 could not save the dim value to the ubrightnesscontroller file. it is a cache file to save and to retrive the brightness value.

would that be correct?

sudo chmod -R 666 "${PLUGIN_DIR}/UBrightnessController/ubrightnesscontroller"
sudo chmod -R 644 "${PLUGIN_DIR}/UBrightnessController/UBrightnessController.py"

it works like that.

**Comment by serdarsen** [comment]
I get it now. v1.2.0 released. it uses .config/ubrightnesscontroller folder.

and

@fossfreedom  this is my new plugin [budgie-browser-profile-launcher](https://github.com/serdarsen/budgie-browser-profile-launcher)
