### ISSUE TITLE
1.2.0 applet runtime issue

### ISSUE THREAD

**Issue by fossfreedom** [serdarsen/budgie-advanced-brightness-controller#4]
On start of the panel I saw the following:

```
Traceback (most recent call last):
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 53, in do_get_panel_widget
    return UBrightnessControllerApplet(uuid)
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 243, in __init__
    self.initBrightness();
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 136, in initBrightness
    self.brightness_settings = self.get_brightness_settings()
  File "/usr/lib/budgie-desktop/plugins/UBrightnessController/UBrightnessController.py", line 96, in get_brightness_settings
    bs = range(0, self.max_brightness, self.max_brightness/self.MAXSTEPS)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by serdarsen** [comment]
I think I have fixed the issue now. if so I will draft a new release. 

sorry forgat push

now done

**Comment by fossfreedom** [comment]
ok - that just produced a range error when trying to use "append" to add to the range.  I think you could be mixing python2 range which returns a list with python3 which returns a range type
```
def get_brightness_settings(self):
        if self.max_brightness < self.MAXSTEPS:
            bs = range(0, self.max_brightness, 1)
        else:
            bs = range(0, self.max_brightness, self.max_brightness//self.MAXSTEPS)
        l = list(bs).append(self.max_brightness)
        return l

```

Possibly you meant to do the above? i.e. cast to list and return that list.

Note - 2 issues:  when starting the panel the brightness appeared to dim by approx 50 %

I manually changed the brightness using my keyboard to maximum but the slider was showing 50.7% - so not sure what is happening here.

Again - if I manually change the brightness using my laptop brightness keys, the slider does not update with the actual dim value.

EDIT: if I removed the ".append (self.max_brightness) then the light slider appears to work ok.

Issue 2: On first startup the whole screen was changed to almost dark - the initial light value should actually be the current brightness value.

Issue 3: I have two sliders - "Light" and "Dim" - both appear to be changing the screen brightness - I don't understand the difference between the two sliders.

**Comment by serdarsen** [comment]
Thank you for your time

1) I was mixing python2 and python3 range type. This code was from original snippet I removed unnecessary lines, edited classes. I hope that it will work perfectly well.

2) Starting low dim value fixed.

3) I couldn't add keyboard support, but now it will update the slider when indicator icon clicked.

4) If I could add keyboard support it will change only the Light slider. Because the Light is equivalent to ubuntu's settings->power->Screen brightness option. 

5) Yes I totally removed codes about range.

6) (Issue 2) I think this was from starting dim value. it is fixed.

7) (Issue 3) Yes we have two sliders. They are slightly different and independent. Light is standart backlight brightness. Dim is more sensitive xrandr brightness. [ According to this comment](https://bugzilla.redhat.com/show_bug.cgi?id=1173945#c1) :

> 1. xrand
> 2. gsd-backlight-helper
> 
> xrandr is using the xorg-intel driver, which itself is searching for the best backlight device in sysfs. As both entries in sysfs are of type firmeware it is selecting the first device it finds which is the not working acpi_video0.
> 
> gsd-backlight-helper works with the sysfs entries, too. It is doing more or less the same selection as the intel driver.

**Comment by fossfreedom** [comment]
looking good - the icon in budgie-settings doesnt appear to be symbolic though

![budgie desktop settings_069](https://user-images.githubusercontent.com/996240/39662658-390bb6a4-505d-11e8-81c1-7161f47774c0.png)

BTW - "U Brightness..." - does the "U" mean anything?

**Comment by serdarsen** [comment]
Ok. I have fixed the symbolic now, didn't push yet. No, "U" isn't mean anything, I actually want to change the plugin and the repository name.

Plugin: Advanced Brightness Controller.
Repo: budgie-advanced-brightness-controller.   

Plugin: Sensitive Brightness Controller.
Repo: budgie-sensitive-brightness-controller.   

or I'm open to suggestions and I can change Light and Dim titles if it not fit.

**Comment by fossfreedom** [comment]
advanced would have my vote 😀

**Comment by serdarsen** [comment]
Done v1.2.3

**Comment by Jacob-Vlijm** [comment]
Advanced Brightness Controller = ABC :)
Goes well well with version 1.2.3  :)

**Comment by fossfreedom** [comment]
ta - have now packaged for Ubuntu and is available to install from our backports repo "budgie-advanced-brightness-controller".  I will add this to budgie-welcome very soon and release it.

Cheers for all your hard work and quick response - it was much appreciated :)

**Comment by fossfreedom** [comment]
This has now been released in budgie-welcome.  The snap should autorefresh after a few minutes/hours on login.

**Comment by serdarsen** [comment]
@fossfreedom I did not see the applet in Budgie welcome

**Comment by Jacob-Vlijm** [comment]
![image](https://user-images.githubusercontent.com/8932980/41091799-b4efba14-6a47-11e8-94d5-cdf3ccc355de.png)
@serdarsen It's there! Welcome > Install Sofware > Budgie Applets

**Comment by serdarsen** [comment]
Ok. I wonder if I'm using the wrong version. This is my fresh installed and updated Ubuntu budgie 18.04 on virtualbox.

![budgie_welcome_screenshot_1](https://user-images.githubusercontent.com/26231317/41133848-ed15ba80-6ad1-11e8-8579-472b3a67bc32.png)
![budgie_welcome_screenshot_2](https://user-images.githubusercontent.com/26231317/41133850-eeec333e-6ad1-11e8-97e1-58dcaa612071.png)
