### ISSUE TITLE
Display2 not dimmed

### ISSUE THREAD

**Issue by JonCGroberg** [serdarsen/budgie-advanced-brightness-controller#5]
Is there a reason display 1 and 2 are assigned but only display 1 is changed
![screenshot from 2018-11-07 17-18-43](https://user-images.githubusercontent.com/26663355/48164723-50f32180-e2b1-11e8-82a7-486222e7b543.png)

**Comment by serdarsen** [comment]
https://github.com/serdarsen/budgie-advanced-brightness-controller/pull/6
