### ISSUE TITLE
Not working with gsd-3.32

### ISSUE THREAD

**Issue by phenonymous** [serdarsen/budgie-advanced-brightness-controller#9]
`gsd-backlight-helper` got changed in gnome-settings-daemon 3.32 to only support writing brightness, see https://github.com/GNOME/gnome-settings-daemon/commit/0d5696f90cd6252f1295d65c2a48d19e1cce6170

This is present in Ubuntu 19.04 and flavours that ships with gnome-settings-daemon 3.32. As a result you can't change the brightness.

Edit: This is the cause of #8

**Comment by serdarsen** [comment]
Thank you @phenonymous your suggestions helped me a lot. I fixed those in v1.3.0
